name: Build
on:
  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore src/Content/Backend

    - name: Build
      run: dotnet build src/Content/Backend --configuration Release

    - name: Run tests
      run: dotnet test src/Content/Backend --configuration Release --no-build
      
    - name: Restore dependencies
      run: dotnet restore src/Content/NetStandardComponent

    - name: Build
      run: dotnet build src/Content/NetStandardComponent --configuration Release

    - name: Run tests
      run: dotnet test src/Content/NetStandardComponent --configuration Release --no-build